# Site settings
title: crowdscreen
email: annmari.darj@gmail.com
description: > # Din väg till miljonen.
baseurl: "" # the sub-path of your site, e.g. /blog/
url: "https://amo222.github.io/" # the base host-name & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown

sass:
    sass_dir: assets/stylesheets
assets:
  sources:
    - assets
    - assets/images
    - assets/stylesheets

navigation:
- text: Beställ
  url: /#order
