# Site settings
title: forstamiljonen.se
email: annmari.darj@gmail.com
description: > # Din väg till miljonen.
baseurl: "" # the sub-path of your site, e.g. /blog/
url: https://forstamiljonen.se/ # the base host-name & protocol for your site
enforce_ssl: forstamiljonen.se   # without any protocol
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown

sass:
    sass_dir: assets/stylesheets
assets:
  sources:
    - assets
    - assets/images
    - assets/stylesheets

navigation:
- text: Beställ
  url: /#order
